### ISSUE TITLE
Improve StreamFormat change

### ISSUE THREAD

**Issue by christophe-calmejane** [christophe-calmejane/Hive#44]
Before changing the stream format using the combo box, try to detect:
* Dangling dynamic mappings (mappings that won't be valid anymore if the channel count of the new format is less than the current one)
* Incompatible sampling rate (if the new sampling rate is not the same than the audio unit's, and no SRC is available)

In such a case, maybe add a new popup that offers to fix this.

**Comment by christophe-calmejane** [comment]
Dangling mappings detection will be added as part of 1.2.8
As for the sampling rate incompatibility, it should actually be handled by the device. It should not offer a stream format it cannot handle (eg. 48kHz format for a 96kHz unit without SRC)

**Comment by masche842** [comment]
Hi Christophe,

I can not see how a device should handle that if it supports more than one sampling rate.
All RME AVB devices for example support all rates from 44.1 kHz to 192 kHz. For each rate there are several stream formats that reflect the possible channel count for that rate and packet format (AAF and AM824).

But the list of stream formats cannot be altered when the Audio Unit is set to a different rate. The only way out would be to have one configuration per sampling rate. This however leads to an awful user experience, especially in setups where the rate changes on a regular basis like recording or mixing studios handling lots of different client projects.

Maybe you have something different in mind? Otherwise I think the best approach is to set the stream format along with the sampling rate, and probably a checkbox to activate this ("Change format with rate").

**Comment by masche842** [comment]
From a studio/recording perspective, it makes sense to avoid sampling rate conversion whenever possible, as it's impacting audio quality.
So my suggestion is that whenever the rate in AUDIO_UNIT is changed, all stream formats are changed along with it to match the new rate, leaving channel count and packet format as is (if possible).
That is what our internal AVDECC controllers are doing when the rate is changed over the web interface or on the display UI.

In Hive this could be activated with a checkbox per clock domain in the clock manager, like this:

<img width="546" alt="Bildschirmfoto 2023-01-09 um 19 19 35" src="https://user-images.githubusercontent.com/180873/211379673-daab4914-dba7-4e4d-b584-d91bc9e9376c.png">

This way, a user is able to set his studio to a different sampling rate in a consistent and convenient manner.

The only downside at the moment: In order to change stream formats, the streams have to be stopped first, which isn't currently allowed by Milan for talker streams. Hive would have to disconnect the streams first, then change the formats, then reconnect. A lot of ceremony, I know, but this is what users have to do manually at the moment. Would be great to give them a hand here!

**Comment by max24192** [comment]
An extra checkbox at the bottom could be used to trigger that behavior (stop streams, set format, restart stream):

<img width="870" alt="image" src="https://user-images.githubusercontent.com/179484/211432665-76e4b703-f51f-4659-885e-9085cd027802.png">

or a dialog: 
"Active streams must be restarted to adjust the stream format to the new sampling rate. Proceed? 
[x] remember my choice 
[Yes] [No]"

Either would be a great addition that would make media clock changes much easier.

**Comment by christophe-calmejane** [comment]
All good ideas, but it will have to wait for Hive 2.0 which will include real user profiles.
Currently Hive is trying to do as little automation as possible since it is targetting developpers and low level users (manual operations). Some automations panes were added to fill a gap and they will be split into profiles for Hive 2.0 with more automations across the board, including smart things like this.

It doesn't mean you cannot contribute changes to the current version, it will be moved to Hive 2.0 afterwards :)

**Comment by christophe-calmejane** [comment]
I've opened #142 to track this. Thanks!
